# Generated by Django 2.0 on 2019-08-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.FileField(default='abc.jpg', upload_to='\\image'),
        ),
    ]
