# Generated by Django 2.0 on 2019-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='abc.jpg', upload_to='\\image'),
        ),
    ]
